### ISSUE TITLE
name=".entry" not available

### ISSUE THREAD

**Issue by SRIKAR-B-S-S** [cttricks/knot#1]
Hi,
I am @SRIKAR-B-S-S
I made an Google Form and opened its Source Code...
And I was searching for `entry`, But I didn't found it.
When I searched on Google it says _It no longer uses name attribution tag_
And I even saw your YouTube video but it is very old( 2018 )
Hope you reply soon and solve it...
Thank You,
Regards,
B.S.S.SRIKAR

**Comment by cttricks** [comment]
Hi,
I have already mentioned this in the ReadMe file. You can easily get entries `entry codes` by creating a prefilled link
